# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(blank=True, default='', max_length=100)),
                ('longitud', models.CharField(blank=True, default='', max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('isEntrada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('idOperador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('apellido', models.CharField(default='', max_length=100)),
                ('cedula', models.CharField(default='', max_length=10)),
                ('telefono', models.CharField(blank=True, default='', max_length=10)),
                ('foto1', models.TextField(blank=True, default='', null=True)),
                ('foto2', models.TextField(blank=True, default='', null=True)),
                ('foto3', models.TextField(blank=True, default='', null=True)),
                ('foto4', models.TextField(blank=True, default='', null=True)),
                ('foto5', models.TextField(blank=True, default='', null=True)),
	       ('estado', models.CharField(default='', max_length=3)),
            ],
        ),

	migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=3)),
            ],
        ),

        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idProyecto', models.AutoField(primary_key=True)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=3)),
            ],
        ),

        migrations.AddField(
            model_name='asistencia',
            name='idOperador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.Operador'),
        ),

	migrations.AddField(
            model_name='operador',
            name='idTipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.TipoUsuario',db_column='idTipoUsuario'),
        ),

        migrations.CreateModel(
            name='ProyectoOperador',
            fields=[
                ('idProyectoOperador', models.AutoField(primary_key=True)),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.Proyecto',db_column='idProyecto')),
                ('idOperador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApi.Operador',db_column='idOperador')),
                ('estado', models.CharField(default='', max_length=3)),
            ],
        ),
    ]
