# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='estado',
            field=models.CharField(default='', max_length=3),
        ),
    ]
